services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres  # Ensure the database starts before the app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Update with your actual password
      POSTGRES_DB: postgres  # Update with your database name

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Update with your actual password
      POSTGRES_DB: postgres  # Update with your database name
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  pgadmin:
#    image: dpage/pgadmin4:9.3.0
#    ports:
#      - "5050:80"
#    volumes:
#      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
#      - ./dev/pgadmin/pgpass:/config/pgpass
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
#    depends_on:
#      - postgres
#    post_start:
#      - command: chmod 600 /config/pgpass
